#!/bin/sh

case `uname -m` in
	x86_64)
                archive='https://repo-feed.flightradar24.com/linux_x86_64_binaries/fr24feed_1.0.34-0_amd64.tgz'
		;;

	i386|i686)
                archive='https://repo-feed.flightradar24.com/linux_x86_binaries/fr24feed_1.0.34-0_i386.tgz'
		;;

	armv7l|armhf)
                archive='https://repo-feed.flightradar24.com/rpi_binaries/fr24feed_1.0.34-0_armhf.tgz'
		;;

	*)
		echo "Unsupported architecture"
		return 1;
esac

wget -O - ${archive}|tar -xzvf - -C /bin --strip 1
